---
- name: Install dependencies
  community.general.pacman:
    name:
      - php-cgi
      - php-fpm
      - php-sqlite
    state: present

- name: Disable systemd-resolved stub listener
  ansible.builtin.lineinfile:
    path: /etc/systemd/resolved.conf
    regexp: "DNSStubListener="
    line: "DNSStubListener=no"
  notify: "restart systemd-resolved"

- name: Install Pi-hole server
  become: true
  become_user: aurmake
  aur:
    name: pi-hole-server

- name: Recursively change ownership of the Pi-hole web directory
  ansible.builtin.file:
    path: /srv/http/pihole
    state: directory
    recurse: true
    owner: root
    group: http

- name: Set up PHP
  ansible.builtin.lineinfile:
    path: /etc/php/php.ini
    regexp: ";{{ item }}"
    line: "{{ item }}"
  loop:
    - "extension=pdo_sqlite"
    - "extension=sockets"
    - "extension=sqlite3"
  notify: "reload nginx"

- name: Set up nginx virtual host
  ansible.builtin.copy:
    src: pihole.conf
    dest: /etc/nginx/sites-available/pihole.conf
    owner: root
    group: root
    mode: '644'
  notify: "reload nginx"

- name: Optimize for solid state drives
  ansible.builtin.lineinfile:
    path: /etc/pihole/pihole-FTL.conf
    regexp: "#DBINTERVAL"
    line: "DBINTERVAL=60.0"
  notify: "restart pihole-FTL"

- name: Limit maximum log period to a month
  ansible.builtin.lineinfile:
    path: /etc/pihole/pihole-FTL.conf
    regexp: "#MAXDBDAYS"
    line: "MAXDBDAYS=60"
  notify: "restart pihole-FTL"

- name: Ensure /etc/systemd/system/php-fpm.service.d/ exists
  ansible.builtin.file:
    path: "/etc/systemd/system/php-fpm.service.d/"
    owner: root
    group: root
    mode: '755'
    state: directory

- name: Install PHP-FPM unit file
  ansible.builtin.copy:
    src: php-fpm.service
    dest: /etc/systemd/system/php-fpm.service.d/pihole.conf
    owner: root
    group: root
    mode: '644'

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true

- name: Enable PHP-FPM
  ansible.builtin.service:
    name: php-fpm
    enabled: true
    state: started

- name: Enable Pi-hole FTL
  ansible.builtin.service:
    name: pihole-FTL
    enabled: true
    state: started
