---
- name: Install dependencies
  community.general.pacman:
    name:
      - nginx-mainline
      - php-cgi
      - php-fpm
      - php-sqlite
    state: present

- name: Install Pi-hole server
  become: true
  become_user: aurmake
  aur:
    name: pi-hole-server

- name: Set up PHP
  lineinfile:
    path: /etc/php/php.ini
    regexp: ";{{ item }}"
    line: "{{ item }}"
  loop:
    - "extension=pdo_sqlite"
    - "extension=sockets"
    - "extension=sqlite3"
  notify: "reload nginx"

- name: Set up nginx virtual host
  copy:
    src: pihole.conf
    dest: /etc/nginx/sites-available/pihole.conf
  notify: "reload nginx"

- name: Optimize for solid state drives
  lineinfile:
    path: /etc/pihole/pihole-FTL.conf
    regexp: "#DBINTERVAL"
    line: "DBINTERVAL=60.0"
  notify: "restart pihole-FTL"

- name: Limit maximum log period to a month
  lineinfile:
    path: /etc/pihole/pihole-FTL.conf
    regexp: "#MAXDBDAYS"
    line: "MAXDBDAYS=60"
  notify: "restart pihole-FTL"

- name: Ensure /etc/systemd/system/php-fpm.service.d/ exists
  file:
    path: "/etc/systemd/system/php-fpm.service.d/"
    owner: root
    group: root
    mode: 0755
    state: directory

- name: Install PHP-FPM unit file
  copy:
    src: php-fpm.service
    dest: /etc/systemd/system/php-fpm.service.d/pihole.conf
    owner: root
    group: root
    mode: 0644

- name: Reload systemd daemon
  systemd:
    daemon_reload: true

- name: Disable systemd-resolved
  service:
    name: systemd-resolved
    enabled: false
    state: stopped
  notify: "reload nginx"

- name: Enable PHP-FPM
  service:
    name: php-fpm
    enabled: true
    state: started

- name: Enable nginx
  service:
    name: nginx
    enabled: true
    state: started

- name: Enable Pi-hole FTL
  service:
    name: pihole-FTL
    enabled: true
    state: started
