---
- name: Reload PHP-FPM
  ansible.builtin.service:
    name: php-fpm
    state: restarted
  listen: "restart php-fpm"

- name: Reload nginx
  ansible.builtin.service:
    name: nginx
    state: reloaded
  listen: "reload nginx"

- name: Reload pihole-FTL
  ansible.builtin.service:
    name: pihole-FTL
    state: restarted
  listen: "restart pihole-FTL"

- name: Restart systemd-resolved
  ansible.builtin.service:
    name: systemd-resolved
    state: restarted
  listen: "restart systemd-resolved"

