---
- name: Reload PHP-FPM
  service:
    name: php-fpm
    state: restarted
  listen: "restart php-fpm"

- name: Reload nginx
  service:
    name: nginx
    state: reloaded
  listen: "reload nginx"

- name: Reload pihole-FTL
  service:
    name: pihole-FTL
    state: restarted
  listen: "restart pihole-FTL"
