---
- name: Reload lighttpd
  service:
    name: lighttpd
    state: restarted
  listen: "restart lighttpd"

- name: Reload pihole-FTL
  service:
    name: pihole-FTL
    state: restarted
  listen: "restart pihole-FTL"
